/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PetGuardianManagement.GUI.Cart.main;

import PetGuardianManagement.BUS.CartBUS;
import PetGuardianManagement.ExtendFunctions;
import PetGuardianManagement.GUI.BuyTicket.swing.ScrollBar;
import PetGuardianManagement.GUI.Cart.component.Item;
import PetGuardianManagement.GUI.Cart.model.ModelItem;
import PetGuardianManagement.GUI.homepageUser.main.homepageUser;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author ductt
 */
public class Cart extends javax.swing.JPanel {

    private long tongTien;
    private long soDu;

    public Cart() {
        initComponents();
        panelScroll.setVerticalScrollBar(new ScrollBar());
        loadData();
        loadTongTien();
    }

    public void loadData() {
        panelItem.removeAll();
        for (int i = 0; i < CartBUS.getInstance().getLstModelItemSize(); i++) {
            ModelItem modelItem = CartBUS.getInstance().getModelItem(i);
            addItem(modelItem);
        }
        soDu = CartBUS.getInstance().getSoDuKhachHang();
        lbSoDu.setText(ExtendFunctions.CurrencyFormat(soDu));
    }

    public void loadTongTien() {
        tongTien = 0;
        for (int i = 0; i < CartBUS.getInstance().getLstModelItemSize(); i++) {
            ModelItem modelItem = CartBUS.getInstance().getModelItem(i);
            tongTien += modelItem.getLoaiVe().getLGiaVe() * modelItem.getSoLuong();
        }
        lbTongTien.setText(ExtendFunctions.CurrencyFormat(tongTien));
    }

    private void addItem(ModelItem data) {
        Item item = new Item();
        item.setData(data);

        panelItem.add(item);
        panelItem.repaint();
        panelItem.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        lbSoDu = new javax.swing.JLabel();
        header = new PetGuardianManagement.GUI.Cart.component.Header();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panelScroll = new javax.swing.JScrollPane();
        panelItem = new PetGuardianManagement.GUI.BuyTicket.swing.PanelItem();
        btnThanhToan = new PetGuardianManagement.GUI.Signin.swing.Button();
        Title1 = new javax.swing.JLabel();
        lbTongTien = new javax.swing.JLabel();

        setOpaque(false);

        Title.setFont(new java.awt.Font("Cooper", 0, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(243, 148, 34));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Số dư:");

        lbSoDu.setFont(new java.awt.Font("Cooper", 0, 24)); // NOI18N
        lbSoDu.setForeground(new java.awt.Color(243, 148, 34));
        lbSoDu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSoDu.setText("0 ₫");

        jLabel12.setFont(new java.awt.Font("Cooper", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(136, 136, 136));
        jLabel12.setText("Tên Vé");

        jLabel13.setFont(new java.awt.Font("Cooper", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(136, 136, 136));
        jLabel13.setText("Số Lượng");

        jLabel14.setFont(new java.awt.Font("Cooper", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(136, 136, 136));
        jLabel14.setText("Giá");

        jLabel15.setFont(new java.awt.Font("Cooper", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(136, 136, 136));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Số Tiền");

        jLabel16.setFont(new java.awt.Font("Cooper", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(136, 136, 136));
        jLabel16.setText("Thao tác");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(40, 40, 40))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelScroll.setBorder(null);
        panelScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        panelScroll.setViewportView(panelItem);

        btnThanhToan.setBackground(new java.awt.Color(238, 77, 45));
        btnThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhToan.setText("Thanh Toán");
        btnThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThanhToanMouseClicked(evt);
            }
        });

        Title1.setFont(new java.awt.Font("Cooper", 0, 24)); // NOI18N
        Title1.setForeground(new java.awt.Color(243, 148, 34));
        Title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title1.setText("Tổng thanh toán:");

        lbTongTien.setFont(new java.awt.Font("Cooper", 0, 24)); // NOI18N
        lbTongTien.setForeground(new java.awt.Color(243, 148, 34));
        lbTongTien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTongTien.setText("0 ₫");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(429, Short.MAX_VALUE)
                        .addComponent(Title1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTongTien)
                        .addGap(18, 18, 18)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Title)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbSoDu)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(panelScroll))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title)
                    .addComponent(lbSoDu))
                .addGap(18, 18, 18)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(Title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThanhToanMouseClicked
        // Check if SoDu of KhachHang enough
        if (soDu >= tongTien) {
            // Minus SoDu
            if (CartBUS.getInstance().updateSoDuKhachHang(soDu - tongTien) > 0) {
                // Create HoaDon
                int iMaHD = CartBUS.getInstance().createHoaDon(new Date(), tongTien);
                if (iMaHD > 0) {
                    // Create ChiTietHoaDons
                    if (CartBUS.getInstance().createChiTietHoaDons(iMaHD) > 0) {
                        // Create Ve
                        if (CartBUS.getInstance().createVes() > 0) {
                            // Delete All ChiTietGioHang
                            if (CartBUS.getInstance().deleteAllChiTietGioHang() > 0) {
                                // Clear lstModelItem(CartBUS)
                                CartBUS.getInstance().clearLstModelItem();

                                // Delete GioHang
                                if (CartBUS.getInstance().deleteGioHang() > 0) {
                                    JOptionPane.showMessageDialog(null, "Thanh toán thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                                    // Hiển thị cartEmpty
                                    homepageUser.getInstance().setForm(homepageUser.getInstance().cartEmpty);
                                } else {
                                    JOptionPane.showMessageDialog(null, "Xóa giỏ hàng thất bại. Vui lòng thử lại sau.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                                }

                            } else {
                                JOptionPane.showMessageDialog(null, "Xóa Chi Tiết Giỏ Hàng thất bại. Vui lòng thử lại sau.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Tạo vé thất bại. Vui lòng thử lại sau.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Tạo Chi Tiết Hóa Đơn thất bại. Vui lòng thử lại sau.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Tạo Hóa Đơn thất bại. Vui lòng thử lại sau.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Cập nhật số dư thất bại. Vui lòng thử lại sau.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Số dư không đủ. Vui lòng nạp thêm.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThanhToanMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Title1;
    private PetGuardianManagement.GUI.Signin.swing.Button btnThanhToan;
    private PetGuardianManagement.GUI.Cart.component.Header header;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel lbSoDu;
    private javax.swing.JLabel lbTongTien;
    private PetGuardianManagement.GUI.BuyTicket.swing.PanelItem panelItem;
    private javax.swing.JScrollPane panelScroll;
    // End of variables declaration//GEN-END:variables
}
