/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PetGuardianManagement.GUI.Cart.main;

import PetGuardianManagement.DTO.LoaiVeDTO;
import PetGuardianManagement.GUI.BuyTicket.swing.ScrollBar;
import PetGuardianManagement.GUI.Cart.component.Item;

/**
 *
 * @author ductt
 */
public class Cart extends javax.swing.JPanel {

    /**
     * Creates new form Cart
     */
    public Cart() {
        initComponents();
        panelScroll.setVerticalScrollBar(new ScrollBar());
        init();
    }

    private void init() {
        // arraylist lstModelItem = Bus read chi tiet gio hang(idKH)
        /*
            for(item : lstModelItem){
                addItem(item);
            }
         */
        addItem(new LoaiVeDTO(1, "Ve Ngay", 3000));
        addItem(new LoaiVeDTO(2, "Ve Tuan", 25000));
        addItem(new LoaiVeDTO(3, "Ve Thang", 950000));
    }

    private void addItem(LoaiVeDTO data) {
        Item item = new Item();
        item.setData(data);

        panelItem.add(item);
        panelItem.repaint();
        panelItem.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        lblSoDu = new javax.swing.JLabel();
        header = new PetGuardianManagement.GUI.Cart.component.Header();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panelScroll = new javax.swing.JScrollPane();
        panelItem = new PetGuardianManagement.GUI.BuyTicket.swing.PanelItem();
        button1 = new PetGuardianManagement.GUI.Signin.swing.Button();
        Title1 = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();

        setOpaque(false);

        Title.setFont(new java.awt.Font("Cooper", 0, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(243, 148, 34));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Số dư:");

        lblSoDu.setFont(new java.awt.Font("Cooper", 0, 24)); // NOI18N
        lblSoDu.setForeground(new java.awt.Color(243, 148, 34));
        lblSoDu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoDu.setText("0 ₫");

        jLabel12.setFont(new java.awt.Font("Cooper", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(136, 136, 136));
        jLabel12.setText("Tên Vé");

        jLabel13.setFont(new java.awt.Font("Cooper", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(136, 136, 136));
        jLabel13.setText("Số Lượng");

        jLabel14.setFont(new java.awt.Font("Cooper", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(136, 136, 136));
        jLabel14.setText("Giá");

        jLabel15.setFont(new java.awt.Font("Cooper", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(136, 136, 136));
        jLabel15.setText("Số Tiền");

        jLabel16.setFont(new java.awt.Font("Cooper", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(136, 136, 136));
        jLabel16.setText("Thao tác");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(132, 132, 132)
                .addComponent(jLabel13)
                .addGap(98, 98, 98)
                .addComponent(jLabel15)
                .addGap(72, 72, 72)
                .addComponent(jLabel16)
                .addGap(40, 40, 40))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        panelScroll.setBorder(null);
        panelScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        panelScroll.setViewportView(panelItem);

        button1.setBackground(new java.awt.Color(238, 77, 45));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("Mua Hàng");
        button1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        Title1.setFont(new java.awt.Font("Cooper", 0, 24)); // NOI18N
        Title1.setForeground(new java.awt.Color(243, 148, 34));
        Title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title1.setText("Tổng thanh toán:");

        lblTongTien.setFont(new java.awt.Font("Cooper", 0, 24)); // NOI18N
        lblTongTien.setForeground(new java.awt.Color(243, 148, 34));
        lblTongTien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTongTien.setText("0 ₫");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(429, Short.MAX_VALUE)
                        .addComponent(Title1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTongTien)
                        .addGap(18, 18, 18)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Title)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSoDu)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelScroll))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title)
                    .addComponent(lblSoDu))
                .addGap(18, 18, 18)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Title1)
                        .addComponent(lblTongTien))
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Title1;
    private PetGuardianManagement.GUI.Signin.swing.Button button1;
    private PetGuardianManagement.GUI.Cart.component.Header header;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel lblSoDu;
    private javax.swing.JLabel lblTongTien;
    private PetGuardianManagement.GUI.BuyTicket.swing.PanelItem panelItem;
    private javax.swing.JScrollPane panelScroll;
    // End of variables declaration//GEN-END:variables
}
