/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PetGuardianManagement.GUI.BuyTicket.main;

import PetGuardianManagement.GUI.BuyTicket.component.Item;
import PetGuardianManagement.GUI.BuyTicket.model.ModelItem;
import PetGuardianManagement.GUI.BuyTicket.swing.ScrollBar;

/**
 *
 * @author DucTran
 */
public class BuyTicket extends javax.swing.JPanel {

    private int round = 20;

    public BuyTicket() {
        initComponents();
        panelScroll.setVerticalScrollBar(new ScrollBar());
        init();
    }

    private void init() {
        addItem(new ModelItem(1, "Ve Ngay", 3000));
        addItem(new ModelItem(2, "Ve Tuan", 25000));
        addItem(new ModelItem(3, "Ve Thang", 95000));
        addItem(new ModelItem(1, "Ve Ngay", 3000));
        addItem(new ModelItem(2, "Ve Tuan", 25000));
        addItem(new ModelItem(3, "Ve Thang", 95000));
        addItem(new ModelItem(1, "Ve Ngay", 3000));
        addItem(new ModelItem(2, "Ve Tuan", 25000));
        addItem(new ModelItem(3, "Ve Thang", 95000));
    }

    public void addItem(ModelItem data) {
        Item item = new Item();
        item.setData(data);

        panelItem.add(item);
        panelItem.repaint();
        panelItem.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelScroll = new javax.swing.JScrollPane();
        panelItem = new PetGuardianManagement.GUI.BuyTicket.swing.PanelItem();

        setOpaque(false);

        panelScroll.setBorder(null);
        panelScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        panelScroll.setViewportView(panelItem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelScroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelScroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private PetGuardianManagement.GUI.BuyTicket.swing.PanelItem panelItem;
    private javax.swing.JScrollPane panelScroll;
    // End of variables declaration//GEN-END:variables
}
